const tileHTML = '<div class="tile"> </div>'
const rowHTML = '<div class="row"></div>'
const gridHTML = '<div data-guess-grid class="guess-grid"></div>'
const rowsHTML = '<div class="grid-rows"></div>'
const gridTitleHTML = '<div class="grid-title"></div>'